defaults:
    - override hydra/launcher: submitit_local

# environment
task: tie_unknot #
obs: rgb #
episodic: true #
num_envs: 16  #
task_max_n_states:
task_max_n_crossings:
r_gc_allow_flipped_or_mirrored: false

# evaluation
checkpoint: ???
eval_episodes: 16 # DEBUG
eval_freq: 10_000  # belongs to tr split (not eval split)

# training
steps: 10_000_000
batch_size: 256
steps_per_update: 1
reward_coef: 0.1
value_coef: 0.1
termination_coef: 1
consistency_coef: 20
rho: 0.5  # TODO: 0.7 for episodic mujoco tasks 
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995  # TODO: 0.99 for episodic mujoco tasks
buffer_size: 1_000_000
buffer_prefetch: 0
exp_name: default
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 5  
# for rgb: model_size=1 throws a shape mismatch in self.model.pi and z=self.model.encode(obs, task)
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: knots-dev-tdmpc2  #
wandb_entity: zc478  #
wandb_silent: false
wandb_note:
enable_wandb: true
save_csv: true
save_train_json: true

# misc
compile: true  #
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: results-baselines-tdmpc2  #
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???  # must specify for mujoco- or knot- tasks
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
override_seed_steps: ???  # must be multiples of num_envs to take effect
bin_size: ???
